version: "3.7"
services:
  web:
    image: assetstorm/assetstorm:latest
    depends_on: 
      - postgres
    environment:
      LC_ALL: C.UTF-8
      AS_POSTGRES_USER: assetstorm
      AS_POSTGRES_PASSWORD: test
      AS_POSTGRES_DB: assetstorm
      AS_POSTGRES_HOST: postgres
      AS_DEBUG: 'True'
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: assetstorm
      POSTGRES_PASSWORD: cttest
      POSTGRES_DB: assetstorm 
  nginx:
    restart: always
    image: assetstorm/nginx-python:latest
    ports: 
      - "89:80"
    depends_on:
      - web
    environment:
      - PYTHON_HOST=web