version: '3.4'
services:
  db:
    image: postgres:10.1-alpine
    # configure
    # - logging, we want to see all statements. setting `log_min_duration_statement` causes to
    #   log to the same line (better than `log_statement` and `log_duration`)
    # - performance, memory settings assume you have 8+ GB of RAM
    command: >
      postgres
        -c log_destination=stderr
        -c logging_collector=off
        -c log_min_duration_statement=0
        -c max_wal_size=2GB
        -c debug_pretty_print=on
        -c log_checkpoints=on
        -c shared_buffers=1000MB
        -c effective_cache_size=2155MB
        -c checkpoint_completion_target=0.8
        -c work_mem=8MB
    ports:
      - 127.0.0.1:5436:5432
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: asst_dev
    volumes:
      - asst_dev_pg_data:/var/lib/postgresql/data:delegated
    expose:
      - 5432


volumes:
  asst_dev_pg_data:
