version: '3.4'
services:
  assetstorm-postgres:
    image: postgres:alpine
    restart: unless-stopped
    # configure
    # - logging, we want to see all statements. setting `log_min_duration_statement` causes to
    #   log to the same line (better than `log_statement` and `log_duration`)
    # - performance, memory settings assume you have 8+ GB of RAM
    command: >
      postgres
        -c log_destination=stderr
        -c logging_collector=off
        -c log_min_duration_statement=0
        -c max_wal_size=2GB
        -c debug_pretty_print=on
        -c log_checkpoints=on
        -c shared_buffers=1000MB
        -c effective_cache_size=2155MB
        -c checkpoint_completion_target=0.8
        -c work_mem=8MB
    ports:
      - 5432:5432
    environment:
      LC_ALL: "C.UTF-8"
      POSTGRES_USER: "assetstorm"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "assetstorm"
