# Generated by Django 2.2.4 on 2019-08-27 14:46

from django.db import migrations


def create_basic_types(apps, schema_editor):
    model_asset_type = apps.get_model('assets', 'AssetType')
    text = model_asset_type(type_name="text", schema={})
    text.save()
    uri_element = model_asset_type(type_name="uri-element", schema={})
    uri_element.save()
    enum = model_asset_type(type_name="enum", schema={})
    enum.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_basic_types)
    ]
